### ISSUE TITLE
onDebugOverlay NullPointerException

### ISSUE THREAD

**Issue by exys228** [djpadbit/Sound-Physics#7]
[Here's the crashlog](https://github.com/djpadbit/Sound-Physics/files/3070994/crash-2019-04-11_14.44.11-client.txt). Happens on an attempt to connect to server (on world loaded). Restarting MC didn't help, but removing the .cfg file did (from that I assume that Config class is null for some reason?)

**Comment by exys228** [comment]
[Here's](https://github.com/djpadbit/Sound-Physics/files/3071056/soundphysics.cfg.txt) my config file that I deleted.

**Comment by djpadbit** [comment]
This is pretty odd, i seemed to be able to recreate the crash only with a developpement version that had some extra stuff and that crashed the sound thread but i can't seem to recreate the crash with a fresh version from master. Did you hear sounds in the menu before the crash ? And it would help me if you could provide the log from the game.

**Comment by exys228** [comment]
Truly sorry, forgot about the [main thing](https://github.com/djpadbit/Sound-Physics/files/3074567/2019-04-11-3.log)... Same happened on my friend's client, absolutely identical crashlog. I don't exactly remember about hearing any stuff from menu, but if there were no sounds I thing I would notice that.

**Comment by djpadbit** [comment]
That's what i thought, there was a problem with the SoundManager (in that case OpenAL didn't load because it couldn't find it), so Sound Physics didn't get his config loaded and minecraft crashed when you loaded a world.
```
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: Initializing LWJGL OpenAL
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[14:31:32] [Thread-266/ERROR] [net.minecraft.client.audio.SoundManager]: Error in class 'LibraryLWJGLOpenAL'
[14:31:32] [Thread-266/ERROR] [net.minecraft.client.audio.SoundManager]: Unable to initialize OpenAL.  Probable cause: OpenAL not supported.
[14:31:32] [Thread-266/WARN] [net.minecraft.client.audio.SoundManager]: ERROR MESSAGE:
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: Could not locate OpenAL library.
[14:31:32] [Thread-266/WARN] [net.minecraft.client.audio.SoundManager]: STACK TRACE:
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: org.lwjgl.openal.AL.create(AL.java:156)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: org.lwjgl.openal.AL.create(AL.java:102)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: org.lwjgl.openal.AL.create(AL.java:206)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: paulscode.sound.libraries.LibraryLWJGLOpenAL.init(LibraryLWJGLOpenAL.java:164)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1576)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
[14:31:32] [Thread-266/INFO] [net.minecraft.client.audio.SoundManager]: paulscode.sound.CommandThread.run(CommandThread.java:121)
[14:31:32] [Sound Library Loader/WARN] [net.minecraft.client.audio.SoundManager]: ERROR MESSAGE:
[14:31:32] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Could not locate OpenAL library.
[14:31:32] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...
[14:31:32] [Thread-268/INFO] [net.minecraft.client.audio.SoundManager]: Switching to No Sound
[14:31:32] [Thread-268/INFO] [net.minecraft.client.audio.SoundManager]: (Silent Mode)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.UnsatisfiedLinkError: org.lwjgl.openal.ALC10.nalcGetCurrentContext()J
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.ALC10.nalcGetCurrentContext(Native Method)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.lwjgl.openal.ALC10.alcGetCurrentContext(ALC10.java:308)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.sonicether.soundphysics.SoundPhysics.setupEFX(SoundPhysics.java:266)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.sonicether.soundphysics.SoundPhysics.init(SoundPhysics.java:110)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.<init>(SoundManager.java:583)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.client.audio.SoundManager$SoundSystemStarterThread.<init>(SoundManager.java:580)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.client.audio.SoundManager$1.run(SoundManager.java:142)
[14:31:33] [Sound Library Loader/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
```
I should probably check if the sound manager errors out before trying to use OpenAL functions to avoid crashes like theses though.

**Comment by djpadbit** [comment]
It should be fixed in https://github.com/djpadbit/Sound-Physics/commit/d2b5fcd77719d6cc7957c26541f537be212ac35a so i'll close this issue but if it happens again feel free to reopen it
